language: php

matrix:
    include:
        - php: 7.0
        - php: 7.1
        - php: 7.2
        - php: nightly
    fast_finish: true
    allow_failures:
        - php: nightly

before_install:
    - phpenv config-rm xdebug.ini || true
    - composer config --global github-oauth.github.com $GITHUB_TOKEN
install: composer install --prefer-dist --no-progress --no-interaction --no-dev
script: bin/run

env:
    global:
        - secure: "DC1hBoD7khVN/xwSytbD4x/c63clIa6lpnT1TmEgedFnmcjTI41k5bjyfs355F0YCX9fXDa3RINaCQmdKtaS4ZcVvO7/nmXtNRlGoZKoeeiZhAoK0z4HPfkkvK2Do9GLlCqlDET/9CQLJ1M/hPisqJ87qbs0l421x6p29mdQQ7GP1ElZyrMOV7c2WmHn7w3S4MxGGr6pT5nP9XXCYz1tZGD2GiJ37c6oUaIM0GpH8udluCxOyEORIzEV/SffNmRMUo/Kd5ihF0PGbpc+bQUwEoB7HtIOvbnGRtA9pIuUmSWlMgprHi41d9Zvz0/H1BG/5sbxQX6lF16fCaK4m6DPPTxBobcQUhguv1vHq1JPZrRGk52DOzEoZpMqNsxElOJ86O2GPwB30ykQQS8JcIRS4MpbGL7UvNKdqRpMohJ3DA4ujxeszFfl4jOubxQIkYx/+50G0HvMgdSzPxbButSctiTxV403sM6j3U9agLEbli28m4+FMCYzHDh1mDx0kn7WRVYEYY0WJkwMewlyyg4fO8iqCCwoy+PFQYe3MYSvu7FJYJKG9uCybZ0iPY/BF6KQuilOsGHK1GHIWxEH6cyFhp7BtbnOeaSU/0egr82aPVbfLDpRmdMSdBhnQS7A59EHKR7cOpZgaIg3D7vn83S70v/1gg9vm/vf05L7Jttmh4Y="

cache:
    directories:
        - $HOME/.composer

sudo: false
