language: php

matrix:
    include:
        - php: 5.3
        - php: 5.4
        - php: 5.5
        - php: 5.6
        - php: 7.0
        - php: 7.1
        - php: nightly
        - php: hhvm-3.6
          sudo: required
          dist: trusty
          group: edge
        - php: hhvm-3.9
          sudo: required
          dist: trusty
          group: edge
        - php: hhvm-3.12
          sudo: required
          dist: trusty
          group: edge
        - php: hhvm-3.15
          sudo: required
          dist: trusty
          group: edge
        - php: hhvm-3.15
          sudo: required
          dist: trusty
          group: edge
          env: HHVMPHP7=1
        - php: hhvm-nightly
          sudo: required
          dist: trusty
          group: edge
    fast_finish: true
    allow_failures:
        - php: nightly
        - php: hhvm-nightly

before_install:
    - phpenv config-rm xdebug.ini || true
    - composer config --global github-oauth.github.com $GITHUB_TOKEN
install: composer install --prefer-dist --no-progress --no-interaction --optimize-autoloader --ignore-platform-reqs
before_script:
  - if [[ "$HHVMPHP7" ]]; then echo hhvm.php7.all=1 >> /etc/hhvm/php.ini; fi
script: make benchmarks

env:
    global:
        - secure: "IUFNfoOEcg+2hqlfyAyoMyGdHZWrzVvInFISrVSmsflI9g314+z+0SZnKQ5hcKOhAneBbyHvRxXj5jsg4a9lphbtSj0HPQuQAN45u+9oSF8cGlfwEj6AepavT0+wpyiUhJXzZr6VaksdthoA7aY5VgVlB6yKIaz15NREABpff7z9J5O/1yJGix9NydkQ+psjs1CLs71H9kihD4B/nzrW1zHlRsnb1g8WJlRuymtgAVqkfBy0xc3atIDe4/Rw5ihdzDh8Kc164eVJovlrZdVlzHPQSMzLYCrzE13Hf+6Mt47jmBeDsH5slPeyEJ5EgEhkyQO1MSICsZRcRELKr0g5Rlxfj63tTTruC26f/0B78bXXIFw4+ccejcTLoH44vDP6py3W7kKAHJ32Mi0LCnXme9/8SpkeZwwiCpRQE8itSqqLFY8vzmxGbr3LYhuQKxnFJ/L1khm5lBFOQWosvkF9Y5Xf9t9kd2eTSVg0FUnmvZmyABN2fLRyi+qxBCWUtsqt2iao+VCpTFHDr5XP5NbAL3BpIHh3KuQWqymQ2VrTDGlH2/jK/D4RhtnfbHN//T+PLSV4asNHDHREmUmaup1j2feartOIKLDqrlNv3QJKYhElTGIlM/CXysz1/dwaFEbG6ZxSD/uRBc+vSm3bK5O5o8a3NHUmrNUemAEVgc3TZUE="

cache:
    directories:
        - $HOME/.composer

sudo: false
